name: Bug Report
description: Report a bug or unexpected behavior.
type: Bug

body:
       
  - type: markdown
    attributes:
      value: "## Classification"
      description:  Please provide as much information as possible. Initial classification helps automate triage and may be updated later.

  - type: dropdown
    id: product
    attributes:
      label: Product
      options:
        - ScriptSure
        - VetWay
        - Exchange

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Prod Critical
        - P0
        - P1
        - P2
        - P3

  - type: dropdown
    id: source
    attributes:
      label: Source
      options:
        - Customer
        - QA
        - Demo
        - Support
        - Internal Testing
        - Other

  - type: markdown
    attributes:
      value: "## Details"

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the issue.
      placeholder: One or two sentences describing the problem.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to...
        2. Click...
        3. Enter...
        4. Observe...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Supporting Information"

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        Environment:
        User Type:
        User Email:
        Browser:
        OS:
        Version:

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Include screenshots, recordings, logs, stack traces, or any other helpful information.
