name: Bug Report
description: Report a bug or unexpected behavior.
type: Bug

body:
  - type: markdown
    attributes:
      value: |
        Please provide enough information for someone else to understand, reproduce, and prioritize the issue.

  - type: markdown
    attributes:
      value: "## Bug Details"

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the issue.
      placeholder: |
        Describe what happened and why it is a problem.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the issue. If you're unsure, describe what you were doing when you encountered it.
      placeholder: |
        1. Go to...
        2. Click...
        3. Enter...
        4. Observe...
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Classification"

  - type: dropdown
    id: product
    attributes:
      label: Product
      multiple: true
      description: Which product is affected?
      options:
        - ScriptSure
        - VetWay
        - Exchange
      default:
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      multiple: true
      description: Select your best estimate. This may be updated during triage.
      options:
        - Prod Critical
        - P0
        - P1
        - P2
        - P3
    validations:
      required: true

  - type: dropdown
    id: source
    attributes:
      label: Source
      multiple: true
      description: How was this issue discovered?
      options:
        - Customer
        - QA
        - Demo
        - Support
        - Internal Testing
        - Other
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Supporting Information"

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include any relevant environment information.
      placeholder: |
        - Environment:
        - User Type:
        - User Email:
        - Browser:
        - Operating System:
        - Version:

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Include any additional information that may help diagnose the issue.
