name: Sync ScriptSure Project

on:
  issues:
    types:
      - edited
      - labeled
      - unlabeled
      - reopened

permissions:
  contents: read
  issues: read

# Prevent multiple runs for the same issue.
concurrency:
  group: sync-scriptsure-project-${{ github.event.issue.id }}
  cancel-in-progress: true

env:
  PROJECT_OWNER: Angel-Organization
  PROJECT_OWNER_TYPE: organization
  PROJECT_NUMBER: 1
  PROJECT_ID: PVT_kwDOElfYpM4BeD2H

jobs:

  sync-project:
    runs-on: ubuntu-latest

    steps:
    
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.ACTIONS_APP_ID }}
          private-key: ${{ secrets.ACTIONS_APP_PRIVATE_KEY }}
          owner: ${{ env.PROJECT_OWNER }}

      - name: Synchronize Project
        uses: actions/github-script@v8

        with:
          github-token: ${{ steps.app-token.outputs.token }}

          script: |
            const issue = context.payload.issue;

            /*
             * ============================================================
             * Configuration
             * ============================================================
             */
            
            const Config = {
              // Project level fields and options
              project:{
                fields: {
                  Status: {
                    id: "PVTSSF_lADOElfYpM4BeD2HzhYg1gE",
                    type: "singleSelect",
                    options: {
                      "Blocked": "11a9b027",
                      "Scoping": "6695b6f2",
                      "Todo": "f75ad846",
                      "In Development": "47fc9ee4",
                      "QA Testing": "4b2dec1a",
                      "QA Passed": "9679dba4",
                      "Test": "9c54861d",
                      "Stage": "7e9333bf",
                      "Production": "c93ec73b",
                    }
                  },
                  Sprint: {
                    id: "PVTIF_lADOElfYpM4BeD2HzhYg1m0",
                    type: "iteration"
                  },
                  "Blocked Reason": {
                    type: "singleSelect",
                    id: "PVTSSF_lADOElfYpM4BeD2HzhZGxLM"
                  }
                }
              },

              // Organization-level issue fields and options
              issue: {
                fields: {
                  Priority: {
                    id: "IFSS_kgDOAqcSiw",
                    type: "singleSelect",
                    options: {
                      ProdCritical: "IFSSO_kgDOBKR5-Q"
                    }
                  }
                }
              },
              
              // Issue labels & correspoding project statuses,
              // in order of precedence
              statusRules: [
                ["deployed: PROD", "Production"],
                ["deployed: STAGE", "Stage"],
                ["deployed: TEST", "Test"],
                ["QA Passed", "QA Passed"],
                ["On testing", "QA Testing"],
                ["In development", "In Development"]
              ],
            };

            // Issue priorities that will be automatically assigned to
            // the current sprint
            Config.sprintPriorities = new Set([
              Config.issue.fields.Priority.options.ProdCritical
            ])

            /*
             * ============================================================
             * Helpers
             * ============================================================
             */
            
            async function getProjectItem() {
              // Find the project items associated with this Github issue
              const query = `
                query($owner:String!, $repo:String!, $number:Int!) {
                  repository(owner:$owner, name:$repo) {
                    issue(number:$number) {
                      projectItems(first:100) {
                        nodes {
                          id
                          project {
                            number
                          }
                        }
                      }
                    }
                  }
                }
              `;
            
              const response = await github.graphql(query, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                number: issue.number
              });

              // Get the project item associated with the configured project
              const item = response.repository.issue.projectItems.nodes.find(
                item => item.project.number === Number(process.env.PROJECT_NUMBER)
              );
              
              // Return the Project item ID, or null if the issue is not in the Project.
              return item?.id ?? null;
            
            }
            
            async function getProjectFields(projectItemId) {
              // Get the current values for project fields associated with the issue
              const query = `
                query($id:ID!) {
                  node(id:$id) {
                    ... on ProjectV2Item {
                      fieldValues(first:50) {
                        nodes {
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            name
                            field {
                              ... on ProjectV2SingleSelectField {
                                name
                              }
                            }
                          }
                          ... on ProjectV2ItemFieldTextValue {
                            text
                            field {
                              ... on ProjectV2Field {
                                name
                              }
                            }
                          }
                          ... on ProjectV2ItemFieldIterationValue {
                            title
                            iterationId
                            field {
                              ... on ProjectV2IterationField {
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;
            
              const response = await github.graphql(query, {
                id: projectItemId
              });
            
              const project = {};
            
              // Build a simple object keyed by project field name
              for (const field of response.node.fieldValues.nodes) {
                if (!field.field)continue;
                const fieldName = field.field.name;
            
                project[fieldName] =
                  field.name ??
                  field.text ??
                  field.title ??
                  null;
              }
            
              return project;
            }
            
            async function getCurrentIteration() {
              // Get configured iterations, called "Sprint" in the project
              const query = `
                query($owner:String!, $number:Int!) {
                  organization(login:$owner) {
                    projectV2(number:$number) {
                      field(name:"Sprint") {
                        ... on ProjectV2IterationField {
                          configuration {
                            iterations {
                              id
                              title
                              startDate
                              duration
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;
            
              const response = await github.graphql(query, {
                owner: process.env.PROJECT_OWNER,
                number: Number(process.env.PROJECT_NUMBER)
              });
            
              // Determine which iteration is currently active
              const today = new Date();
            
              return response.organization.projectV2.field.configuration.iterations.find(
                iteration => {
                  const start = new Date(iteration.startDate);
                  const end = new Date(start);
                  end.setDate(end.getDate() + iteration.duration);
            
                  return today >= start && today < end;
                }
              );
            }
            
            async function setProjectField(projectItemId, fieldName, value) {
              // Look up the project fields configured in this action
              const field = Config.project.fields[fieldName];
            
              if (!field)
                throw new Error(`Unknown field: ${fieldName}`);
            
              const input = {
                projectId: process.env.PROJECT_ID,
                itemId: projectItemId,
                fieldId: field.id
              };
            
              // Format the value based on the Project field type
              switch (field.type) {
              
                case "singleSelect":
                  input.value = {singleSelectOptionId: field.options[value]};
                  break;

                  case "multiSelect":
                    input.value = { multiSelectOptionIds: value.map(option => field.options[option])};
                    break;
              
                case "iteration":
                  input.value = {iterationId: value};
                  break;
              
                case "text":
                  input.value = {text: value};
                  break;

                case "date":
                  input.value = {date: value};
                  break;
              
                case "number":
                  input.value = {number: value};
                  break;
              
                default: 
                  throw new Error(`Unsupported field type: ${field.type}`);
              }
            
              // Update the Project field
              await github.graphql(`
                mutation($input:UpdateProjectV2ItemFieldValueInput!) {
                  updateProjectV2ItemFieldValue(input:$input) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `, {
                input
              });
            }

            async function getPriority() {
              // Get the organization issue field values for this issue
              const response = await github.request(
                "GET /repos/{owner}/{repo}/issues/{issue_number}/issue-field-values",
                {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  headers: {
                    "X-GitHub-Api-Version": "2022-11-28"
                  }
                }
              );
            
              // Find the configured Priority field
              const priority = response.data.find(
                field => field.node_id === Config.issue.fields.Priority.id
              );
            
              // Return the priority, if it's supposed to auto-add the issue
              // to the sprint
              return priority?.single_select_option?.node_id ?? null;
            }
            
            /*
             * ============================================================
             * Synchronization
             * ============================================================
             */
            
            // Cache issue labels for quick lookup
            const labels = new Set(issue.labels.map(label => label.name));
            
            async function syncStatus(projectItemId, project) {
              let status = "Todo";

              // If the issue is blocked, it's status is set to "Blocked"
              // regardless of any labels
              if (project["Blocked Reason"]) {
                status = "Blocked";
              } else {
                // Highest precedence label sets the project status
                for (const [label, value] of Config.statusRules) {
                  if (labels.has(label)) {
                    status = value;
                    break;
                  }
                }
              }
            
              // Only update the project if it's current status is different than
              // status identified according to labels/blocked
              if (project.Status !== status) {
                await setProjectField(projectItemId,"Status",status);
              }
            }
            
            async function syncSprint(projectItemId, project) {
              // Only specific priorities get auto-added to the current sprint
              const priority = await getPriority();
            
              if (!Config.sprintPriorities.has(priority)) {
                core.info("Skipping sprint assignment: priority not configured.");
                return;
              }
              
              // Determine the currently active sprint 
              const currentIteration = await getCurrentIteration();
              core.info(`Current iteration: ${currentIteration.title}`);
              core.info(`Project sprint: ${project.Sprint}`);
            
              // Only assign the issue to the current sprint if it isn't in the sprint
              // already
              if (project.Sprint !== currentIteration.title) {
                core.info("Assigning issue to current sprint.");
                await setProjectField(projectItemId,"Sprint",currentIteration.id);
              } else {
                core.info("Issue is already in the current sprint.");
              }
            }

            /*
             * ============================================================
             * Main
             * ============================================================
             */
            
            async function runProjectSync() {
              core.info(`Synchronizing Issue #${issue.number}`);
              // Find the issue's corresponding project item
              const projectItemId = await getProjectItem();  

              // Skip if the issue isn't in the configured project
              if (!projectItemId) {
                core.info("Issue is not in the configured Project. Skipping synchronization.");
                return;
              }
              
              // Retrieve the current project field values
              const project = await getProjectFields(projectItemId);
            
              // Sync project status
              await syncStatus(projectItemId,project);
            
              // See if it needs to get added to the current sprint
              await syncSprint(projectItemId, project);
            
              core.info(`Sync complete.`);
            }
            
            runProjectSync().catch(core.setFailed);
