name: Sync ScriptSure Project

on:
  issues:
    types:
      - edited
      - labeled
      - unlabeled
      - reopened

permissions:
  contents: read
  issues: read

# Prevent multiple runs for the same issue.
concurrency:
  group: sync-scriptsure-project-${{ github.event.issue.id }}
  cancel-in-progress: true

env:
  PROJECT_OWNER: Angel-Organization
  PROJECT_OWNER_TYPE: organization
  PROJECT_NUMBER: 1
  PROJECT_ID: PVT_kwDOElfYpM4BeD2H

jobs:

  sync-project:
    runs-on: ubuntu-latest

    steps:
    
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.ACTIONS_APP_ID }}
          private-key: ${{ secrets.ACTIONS_APP_PRIVATE_KEY }}
          owner: ${{ env.PROJECT_OWNER }}

      - name: Synchronize Project
        uses: actions/github-script@v8

        with:
          github-token: ${{ steps.app-token.outputs.token }}

          script: |
            const issue = context.payload.issue;

            /*
             * ============================================================
             * Configuration
             * ============================================================
             */
            
            const Config = {
              // Project level fields and options
              project:{
                fields: {
                  Status: {
                    id: "PVTSSF_lADOElfYpM4BeD2HzhYg1gE",
                    type: "singleSelect",
                    options: {
                      "Blocked": "11a9b027",
                      "Scoping": "6695b6f2",
                      "Todo": "f75ad846",
                      "In Development": "47fc9ee4",
                      "QA Testing": "4b2dec1a",
                      "QA Passed": "9679dba4",
                      "Test": "9c54861d",
                      "Stage": "7e9333bf",
                      "Production": "c93ec73b",
                    }
                }
              },
              
              // Issue labels & correspoding project statuses,
              // in order of precedence
              statusRules: [
                ["deployed: PROD", "Production"],
                ["deployed: STAGE", "Stage"],
                ["deployed: TEST", "Test"],
                ["QA Passed", "QA Passed"],
                ["On testing", "QA Testing"],
                ["In development", "In Development"]
              ],
            };

            /*
             * ============================================================
             * Helpers
             * ============================================================
             */
            
            async function getProjectItem() {
              // Find the project items associated with this Github issue
              const query = `
                query($owner:String!, $repo:String!, $number:Int!) {
                  repository(owner:$owner, name:$repo) {
                    issue(number:$number) {
                      projectItems(first:100) {
                        nodes {
                          id
                          project {
                            number
                          }
                        }
                      }
                    }
                  }
                }
              `;
            
              const response = await github.graphql(query, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                number: issue.number
              });

              // Get the project item associated with the configured project
              const item = response.repository.issue.projectItems.nodes.find(
                item => item.project.number === Number(process.env.PROJECT_NUMBER)
              );
              
              // Return the Project item ID, or null if the issue is not in the Project.
              return item?.id ?? null;
            
            }
            
            async function getProjectFields(projectItemId) {
              // Get the current values for project fields associated with the issue
              const query = `
                query($id:ID!) {
                  node(id:$id) {
                    ... on ProjectV2Item {
                      fieldValues(first:50) {
                        nodes {
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            name
                            field {
                              ... on ProjectV2SingleSelectField {
                                name
                              }
                            }
                          }
                          ... on ProjectV2ItemFieldTextValue {
                            text
                            field {
                              ... on ProjectV2Field {
                                name
                              }
                            }
                          }
                          ... on ProjectV2ItemFieldIterationValue {
                            title
                            iterationId
                            field {
                              ... on ProjectV2IterationField {
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;
            
              const response = await github.graphql(query, {
                id: projectItemId
              });

              core.info(JSON.stringify(response.node.fieldValues.nodes, null, 2));
              const project = {};
            
              // Build a simple object keyed by project field name
              for (const field of response.node.fieldValues.nodes) {
                if (!field.field)continue;
                const fieldName = field.field.name;
            
                project[fieldName] =
                  field.name ??
                  field.text ??
                  field.title ??
                  null;
              }
            
              return project;
            }
            
            async function setProjectField(projectItemId, fieldName, value) {
              // Look up the project fields configured in this action
              const field = Config.project.fields[fieldName];
            
              if (!field)
                throw new Error(`Unknown field: ${fieldName}`);
            
              const input = {
                projectId: process.env.PROJECT_ID,
                itemId: projectItemId,
                fieldId: field.id
              };
            
              // Format the value based on the Project field type
              switch (field.type) {
              
                case "singleSelect":
                  input.value = {singleSelectOptionId: field.options[value]};
                  break;

                  case "multiSelect":
                    input.value = { multiSelectOptionIds: value.map(option => field.options[option])};
                    break;
              
                case "iteration":
                  input.value = {iterationId: value};
                  break;
              
                case "text":
                  input.value = {text: value};
                  break;

                case "date":
                  input.value = {date: value};
                  break;
              
                case "number":
                  input.value = {number: value};
                  break;
              
                default: 
                  throw new Error(`Unsupported field type: ${field.type}`);
              }
            
              // Update the Project field
              await github.graphql(`
                mutation($input:UpdateProjectV2ItemFieldValueInput!) {
                  updateProjectV2ItemFieldValue(input:$input) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `, {
                input
              });
            }
            
            /*
             * ============================================================
             * Synchronization
             * ============================================================
             */
            
            // Cache issue labels for quick lookup
            const labels = new Set(issue.labels.map(label => label.name));
            
            async function syncStatus(projectItemId, project) {
              let status = "Todo";

              // Highest precedence label sets the project status
              for (const [label, value] of Config.statusRules) {
                if (labels.has(label)) {
                  status = value;
                  break;
                }  
              }
            
              // Only update the project if it's current status is different than
              // status identified according to labels
              if (project.Status !== status) {
                await setProjectField(projectItemId,"Status",status);
              }
            }
            
            /*
             * ============================================================
             * Main
             * ============================================================
             */
            
            async function runProjectSync() {
              core.info(`Synchronizing Issue #${issue.number}`);
              // Find the issue's corresponding project item
              const projectItemId = await getProjectItem();  

              // Skip if the issue isn't in the configured project
              if (!projectItemId) {
                core.info("Issue is not in the configured Project. Skipping synchronization.");
                return;
              }
              
              // Retrieve the current project field values
              const project = await getProjectFields(projectItemId);
            
              // Sync project status
              await syncStatus(projectItemId,project);
            
              core.info(`Sync complete.`);
            }
            
            runProjectSync().catch(core.setFailed);
